from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

reviews = ROOT / "webapp/src/pages/Reviews.jsx"
text = reviews.read_text(encoding="utf-8")
text = text.replace(
    'const REVIEWS_COVER_URL = "https://i.postimg.cc/j2LNsV6J/ec67a9b5ebaf057dfccee73a663f086e.jpg";',
    'const REVIEWS_COVER_URL = "https://i.postimg.cc/x1cssCXT/sa-2.jpg";',
)
text = text.replace('''      <div className="reviews-cover-card animate-in" aria-hidden="true">\n        <img src={REVIEWS_COVER_URL} alt="" />\n        <ThumbsUp className="reviews-cover-like" weight="fill" />\n      </div>\n\n      <div className="reviews-list-head">\n        <div className="reviews-list-title">همهٔ نظرات <span className="reviews-count num">{total.toLocaleString()}</span></div>\n        {isAdmin && <span className="admin-mode-badge"><ShieldCheck size={14} weight="fill" /> مدیریت</span>}\n      </div>\n\n      <section className="review-compose-card animate-in" style={{ animationDelay: "0.04s" }}>\n        <div className="review-compose-title">نظر شما</div>\n        <textarea\n          className="review-textarea"\n          value={body}\n          onChange={(e) => setBody(e.target.value.slice(0, MAX_REVIEW_LENGTH))}\n          placeholder="نظر خود را بنویسید…"\n          maxLength={MAX_REVIEW_LENGTH}\n        />\n        <div className="review-compose-footer">\n          <span className={`review-counter num ${body.length > 740 ? "near-limit" : ""}`}>{body.length}/{MAX_REVIEW_LENGTH}</span>\n          <button type="button" className="review-submit-btn" onClick={submitReview} disabled={!canSubmit}>\n            {submitting ? <span className="spinner" /> : <><PaperPlaneTilt size={16} weight="fill" /> نشر نظر</>}\n          </button>\n        </div>\n      </section>\n\n      {loading && <Skeleton count={4} />}\n''', '''      <div className="reviews-cover-card animate-in" aria-hidden="true">\n        <img src={REVIEWS_COVER_URL} alt="" />\n      </div>\n\n      <div className="reviews-list-head">\n        <div className="reviews-list-title">همهٔ نظرات <span className="reviews-count num">{total.toLocaleString()}</span></div>\n        {isAdmin && <span className="admin-mode-badge"><ShieldCheck size={14} weight="fill" /> مدیریت</span>}\n      </div>\n\n      {loading && <Skeleton count={4} />}\n''')
text = text.replace('''      {!loading && !showAll && hiddenCount > 0 && (\n        <button type="button" className="reviews-show-more" onClick={() => setShowAll(true)}>\n          نمایش بیشتر <span className="num">({hiddenCount.toLocaleString()})</span>\n        </button>\n      )}\n    </div>\n''', '''      {!loading && !showAll && hiddenCount > 0 && (\n        <button type="button" className="reviews-show-more" onClick={() => setShowAll(true)}>\n          نمایش بیشتر <span className="num">({hiddenCount.toLocaleString()})</span>\n        </button>\n      )}\n\n      <section className="review-compose-card animate-in" style={{ animationDelay: "0.04s" }}>\n        <div className="review-compose-title">نظر شما</div>\n        <textarea\n          className="review-textarea"\n          value={body}\n          onChange={(e) => setBody(e.target.value.slice(0, MAX_REVIEW_LENGTH))}\n          placeholder="نظر خود را بنویسید…"\n          maxLength={MAX_REVIEW_LENGTH}\n        />\n        <div className="review-compose-footer">\n          <span className={`review-counter num ${body.length > 740 ? "near-limit" : ""}`}>{body.length}/{MAX_REVIEW_LENGTH}</span>\n          <button type="button" className="review-submit-btn" onClick={submitReview} disabled={!canSubmit}>\n            {submitting ? <span className="spinner" /> : <><PaperPlaneTilt size={16} weight="fill" /> نشر نظر</>}\n          </button>\n        </div>\n      </section>\n    </div>\n''')
reviews.write_text(text, encoding="utf-8")

css = ROOT / "webapp/src/index.css"
styles = css.read_text(encoding="utf-8")
styles = styles.replace('''\n.reviews-cover-like {\n  position: absolute;\n  inset: 50% auto auto 50%;\n  transform: translate(-50%, -50%);\n  width: clamp(72px, 24vw, 122px);\n  height: clamp(72px, 24vw, 122px);\n  color: #fff;\n  opacity: 0.1;\n  pointer-events: none;\n}\n''', '\n')
css.write_text(styles, encoding="utf-8")
