-- Mini App user reviews and official Saraf replies.
-- Access is through the authenticated FastAPI service only; no direct client policies.

create table if not exists public.miniapp_reviews (
    id bigint generated by default as identity primary key,
    chat_id bigint not null,
    display_name text not null check (char_length(display_name) between 1 and 80),
    username text,
    body text not null check (char_length(body) between 3 and 800),
    admin_reply text check (admin_reply is null or char_length(admin_reply) between 3 and 1200),
    admin_replied_at timestamptz,
    is_visible boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists miniapp_reviews_visible_created_idx
    on public.miniapp_reviews (is_visible, created_at desc);

create index if not exists miniapp_reviews_chat_created_idx
    on public.miniapp_reviews (chat_id, created_at desc);

alter table public.miniapp_reviews enable row level security;

comment on table public.miniapp_reviews is
    'User comments shown in the Saraf Mini App. Official replies are written by ADMIN_CHAT_IDS through the server API.';
