-- Saraf Instagram Automation V2
-- Conversation memory + DM idempotency

create table if not exists public.ig_message_events (
    message_id text primary key,
    sender_id text not null,
    message_text text not null default '',
    replied boolean not null default false,
    created_at timestamptz not null default now(),
    processed_at timestamptz
);

create index if not exists idx_ig_message_events_sender_created
    on public.ig_message_events (sender_id, created_at desc);

create table if not exists public.ig_conversation_messages (
    id bigint generated by default as identity primary key,
    instagram_user_id text not null,
    role text not null check (role in ('user', 'assistant')),
    content text not null,
    message_id text,
    created_at timestamptz not null default now()
);

create unique index if not exists uq_ig_conversation_message_id
    on public.ig_conversation_messages (message_id)
    where message_id is not null;

create index if not exists idx_ig_conversation_user_created
    on public.ig_conversation_messages (instagram_user_id, created_at desc);

alter table public.ig_message_events enable row level security;
alter table public.ig_conversation_messages enable row level security;

-- Server-only tables. No public/authenticated policies are added.
-- The backend must use the server-side Supabase key configured for Saraf.
